### ISSUE TITLE
handling a list of tags

### ISSUE THREAD

**Issue by ngosang** [foxmask/wallabag_api#2]
https://github.com/foxmask/wallabag_api/blob/master/wallabag_api/wallabag.py#L297
Should be:
```
params['tags'] = ','.join(tags)
```
You already did here => https://github.com/foxmask/wallabag_api/blob/master/wallabag_api/wallabag.py#L183

Check all tags related lines. Thank you!

**Comment by foxmask** [comment]
Hi, 
Thanks for reporting.
Do not hesitate to make a pull request

**Comment by foxmask** [comment]
thanks for your contribution
