### ISSUE TITLE
get_entry ['content'] in formats other than HTML?

### ISSUE THREAD

**Issue by AMR692** [foxmask/wallabag_api#5]
It would be nice if we could specify the format we wanted the article text in when we use get_entry to fetch an individual entry. Wallabag supports xml, json, txt, csv, pdf, epub, and mobi in addition to the default HTML that this API returns — unless I've missed something?

**Comment by foxmask** [comment]
Did you try to use it ?

The format Can be set when initializing the API like 

```python
Wallabag(extension="epub")
```

That's all

**Comment by AMR692** [comment]
I did try it. Changing the value of "extension" seems to have no effect on what is returned:
    #!/usr/local/bin/python3
    
    from wallabag_api.wallabag import Wallabag
    
    params = {'username': 'xxxxxxxx',
              'password': 'xxxxxxxx',
              'client_id': 'xxxxxxxx',
              'client_secret': 'xxxxxxxx',
              'extension': 'epub'} # 'mobi' gives the exact same results
    my_host = 'https://example.com'

    token = Wallabag.get_token(host = my_host, **params)
    
    wall = Wallabag(host = my_host, client_secret = params['client_secret'], client_id = params['client_id'], token = token)
    
    myWallabag = wall.get_entries()

    allArticles = myWallabag['_embedded']['items']

    path = 'xxxxxxxx/'

    for article in allArticles:
        print(article['id'], article['title'])
        print(article['content'])
        print('******')

**Comment by foxmask** [comment]
Today, end user can export file from the URL http://domain.com/export/unread.epub for example.
And a guy from Wallabag told me this feature will be available for the API for version 2.3.
I reopen the issue to make that check until then .

**Comment by foxmask** [comment]
I've update the lib to match the api 2.2.3
To get article in epub or pdf you will use wall.get_entry_export(entry=1) 
for the moment, my isp connect is out of order so I can't push the improvement right now.

**Comment by foxmask** [comment]
API 2.2.3 compliant 922c47f1cf3493d3e7699dbde4c0d965afffcab1
